// web/src/routes/docs/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  const sections = [
    { id: 'overview', label: 'Overview' },
    { id: 'capabilities', label: 'Capabilities' },
    { id: 'installation', label: 'Installation' },
    { id: 'usage', label: 'Usage' },
    { id: 'configuration', label: 'Configuration' },
    { id: 'auto-start', label: 'Auto-Start' },
  ];

  let activeSection = 'overview';

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) activeSection = entry.target.id;
        });
      },
      { rootMargin: '-30% 0px -60% 0px' }
    );

    sections.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  });
</script>

<svelte:head>
  <title>Docs — MacMonitor</title>
  <meta name="description" content="MacMonitor documentation — installation, configuration, and usage guide." />
</svelte:head>

<div class="docs-root">
  <!-- Sidebar -->
  <aside class="sidebar">
    <div class="sidebar-inner">
      <p class="sidebar-label">Documentation</p>
      <nav>
        {#each sections as { id, label }}
          <a
            href="#{id}"
            class="sidebar-link"
            class:active={activeSection === id}
          >{label}</a>
        {/each}
      </nav>
      <div class="sidebar-divider"></div>
      <a href="https://github.com/dinexh/Monarx" target="_blank" rel="noopener" class="sidebar-github">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
          <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/>
        </svg>
        View on GitHub
      </a>
    </div>
  </aside>

  <!-- Main content -->
  <main class="content">

    <section id="overview" class="doc-section">
      <h1 class="doc-h1">MacMonitor</h1>
      <p class="doc-lead">A lightweight macOS menu bar application for real-time system monitoring.</p>
      <p class="doc-p">
        MacMonitor lives in your macOS menu bar and shows live CPU and memory usage at a glance.
        It uses native macOS APIs — <code>vm_stat</code>, <code>sysctl</code>, and the
        UserNotifications framework — to give you accurate, low-overhead system telemetry without
        running a heavy background service.
      </p>
      <div class="badge-row">
        <span class="badge">Python 3.9+</span>
        <span class="badge">macOS 12+</span>
        <span class="badge">MIT License</span>
        <span class="badge green">v1.0.0</span>
      </div>
    </section>

    <section id="capabilities" class="doc-section">
      <h2 class="doc-h2">Capabilities</h2>

      <div class="cap-grid">
        <div class="cap-card">
          <div class="cap-icon">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></svg>
          </div>
          <div>
            <h3>Native Menu Bar UI</h3>
            <p>The menu bar title updates every 5 seconds: <code>C:XX% M:XX%</code>. When memory pressure or resource usage is elevated, it switches to <code>WARN</code>, <code>HIGH</code>, or <code>STRESS</code> mode automatically.</p>
          </div>
        </div>

        <div class="cap-card">
          <div class="cap-icon">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="M3 9h18M9 21V9"/></svg>
          </div>
          <div>
            <h3>Memory Breakdown</h3>
            <p>MacMonitor reads <code>vm_stat</code> and <code>memory_pressure</code> to split RAM into four categories: <strong>Wired</strong>, <strong>Active</strong>, <strong>Compressed</strong>, and <strong>Cached</strong>. It also tracks lag risk when Compressed exceeds Active memory.</p>
          </div>
        </div>

        <div class="cap-card">
          <div class="cap-icon">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M3 12h3m12 0h3M12 3v3m0 12v3"/></svg>
          </div>
          <div>
            <h3>Process Intelligence</h3>
            <p>The top 5 CPU and memory consumers are listed in the dropdown in real time. You can kill any process directly from the menu without opening Activity Monitor. Chrome, Electron, and Slack are automatically tagged as GPU-heavy.</p>
          </div>
        </div>

        <div class="cap-card">
          <div class="cap-icon">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>
          </div>
          <div>
            <h3>Native Alerts</h3>
            <p>Threshold breaches trigger macOS UserNotifications — the same alert system used by Calendar and Mail. Alerts respect a 120-second cooldown per metric to prevent notification fatigue. Falls back to <code>osascript</code> if the framework is unavailable.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="installation" class="doc-section">
      <h2 class="doc-h2">Installation</h2>
      <p class="doc-p">MacMonitor requires Python 3.9 or later and runs on macOS 12 Monterey and above.</p>

      <h3 class="doc-h3">1. Clone the repository</h3>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> git clone https://github.com/dinexh/Monarx.git MacMonitor</div>
        <div class="code-line"><span class="prompt">$</span> cd MacMonitor</div>
      </div>

      <h3 class="doc-h3">2. Create a virtual environment</h3>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> python3 -m venv .venv</div>
        <div class="code-line"><span class="prompt">$</span> source .venv/bin/activate</div>
      </div>

      <h3 class="doc-h3">3. Install dependencies</h3>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> pip install -r requirements.txt</div>
      </div>
      <p class="doc-note">Dependencies: <code>psutil</code>, <code>rumps</code>, <code>pyobjc-framework-Cocoa</code>, <code>pyobjc-framework-UserNotifications</code></p>
    </section>

    <section id="usage" class="doc-section">
      <h2 class="doc-h2">Usage</h2>
      <p class="doc-p">Run the app with Python from the project root:</p>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> python main.py</div>
      </div>
      <p class="doc-p">
        MacMonitor will appear in your menu bar as <code>C:XX% M:XX%</code> immediately.
        Click it to open the dropdown showing the full system snapshot.
      </p>

      <h3 class="doc-h3">Menu bar states</h3>
      <div class="state-table">
        <div class="state-row">
          <span class="state-code normal">C:43% M:71%</span>
          <span class="state-label">Normal — all metrics within thresholds</span>
        </div>
        <div class="state-row">
          <span class="state-code warn">WARN C:58% M:74%</span>
          <span class="state-label">Memory pressure detected at WARN level</span>
        </div>
        <div class="state-row">
          <span class="state-code high">HIGH C:91% M:83%</span>
          <span class="state-label">Memory pressure is HIGH</span>
        </div>
        <div class="state-row">
          <span class="state-code stress">STRESS C:35% M:76%</span>
          <span class="state-label">Compressed memory exceeds Active memory (lag risk)</span>
        </div>
      </div>
    </section>

    <section id="configuration" class="doc-section">
      <h2 class="doc-h2">Configuration</h2>
      <p class="doc-p">
        Thresholds can be changed at runtime via the <strong>Settings → Change Thresholds</strong> menu item,
        or by editing <code>core/config.py</code>. Saved values persist in
        <code>~/Library/Application Support/MacMonitor/config.json</code>.
      </p>

      <div class="config-table">
        <div class="config-row header">
          <span>Variable</span><span>Default</span><span>Description</span>
        </div>
        <div class="config-row">
          <code>CPU_LIMIT</code><code>85</code><span>Alert when CPU % ≥ this value</span>
        </div>
        <div class="config-row">
          <code>MEM_LIMIT</code><code>80</code><span>Alert when RAM % ≥ this value</span>
        </div>
        <div class="config-row">
          <code>SWAP_LIMIT</code><code>20</code><span>Alert when Swap % ≥ this value</span>
        </div>
        <div class="config-row">
          <code>CHECK_EVERY</code><code>5</code><span>Sampling interval in seconds</span>
        </div>
        <div class="config-row">
          <code>COOLDOWN</code><code>120</code><span>Minimum seconds between repeated alerts</span>
        </div>
      </div>

      <p class="doc-note">
        Lowering <code>CHECK_EVERY</code> increases responsiveness but also CPU usage.
        For battery-sensitive use, consider 10–30 seconds.
      </p>
    </section>

    <section id="auto-start" class="doc-section">
      <h2 class="doc-h2">Auto-Start on Login</h2>
      <p class="doc-p">
        Create a LaunchAgent plist so MacMonitor starts automatically when you log in.
        Replace <code>/path/to/MacMonitor</code> with the absolute path to your clone.
      </p>

      <h3 class="doc-h3">1. Create the plist file</h3>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> nano ~/Library/LaunchAgents/com.macmonitor.plist</div>
      </div>

      <div class="code-block xml">
        <pre>{`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.macmonitor</string>
    <key>ProgramArguments</key>
    <array>
        <string>/path/to/MacMonitor/.venv/bin/python</string>
        <string>/path/to/MacMonitor/main.py</string>
    </array>
    <key>WorkingDirectory</key>
    <string>/path/to/MacMonitor</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>`}</pre>
      </div>

      <h3 class="doc-h3">2. Load the agent</h3>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> launchctl load ~/Library/LaunchAgents/com.macmonitor.plist</div>
      </div>

      <h3 class="doc-h3">Unload / stop</h3>
      <div class="code-block">
        <div class="code-line"><span class="prompt">$</span> launchctl unload ~/Library/LaunchAgents/com.macmonitor.plist</div>
      </div>

      <h3 class="doc-h3">Log files</h3>
      <p class="doc-p">
        MacMonitor writes logs to <code>~/Library/Logs/MacMonitor/macmonitor.log</code>.
        You can open them directly from the menu via <strong>View Logs</strong>.
      </p>
    </section>

    <div class="doc-footer">
      <p>© 2026 MacMonitor · <a href="https://github.com/dinexh/Monarx" target="_blank" rel="noopener">GitHub</a> · MIT License</p>
    </div>
  </main>

  <!-- Right TOC -->
  <div class="toc">
    <p class="toc-label">On this page</p>
    {#each sections as { id, label }}
      <a href="#{id}" class="toc-link" class:active={activeSection === id}>{label}</a>
    {/each}
  </div>
</div>

<style>
  .docs-root {
    display: grid;
    grid-template-columns: 220px 1fr 180px;
    min-height: 100vh;
    padding-top: 60px;
    max-width: 1280px;
    margin: 0 auto;
  }

  /* Sidebar */
  .sidebar {
    position: sticky;
    top: 60px;
    height: calc(100vh - 60px);
    overflow-y: auto;
    border-right: 1px solid var(--border);
    padding: 32px 0;
  }

  .sidebar-inner {
    padding: 0 24px;
  }

  .sidebar-label {
    font-size: 10.5px;
    font-weight: 700;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--text-dim);
    margin-bottom: 12px;
  }

  .sidebar-link {
    display: block;
    padding: 7px 12px;
    font-size: 13.5px;
    color: var(--text-muted);
    border-radius: 6px;
    transition: color 0.15s, background 0.15s;
    margin-bottom: 2px;
    border-left: 2px solid transparent;
  }

  .sidebar-link:hover {
    color: #fff;
    background: var(--white-glow);
  }

  .sidebar-link.active {
    color: #fff;
    border-left-color: #3b82f6;
    background: rgba(59,130,246,0.06);
  }

  .sidebar-divider {
    height: 1px;
    background: var(--border);
    margin: 20px 0;
  }

  .sidebar-github {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 12.5px;
    color: var(--text-dim);
    padding: 6px 12px;
    border-radius: 6px;
    transition: color 0.15s;
  }

  .sidebar-github:hover { color: #fff; }

  /* Content */
  .content {
    padding: 48px 48px 80px;
    min-width: 0;
  }

  .doc-section {
    padding-bottom: 64px;
    border-bottom: 1px solid var(--border);
    margin-bottom: 64px;
  }

  .doc-section:last-of-type {
    border-bottom: none;
  }

  .doc-h1 {
    font-size: 40px;
    font-weight: 700;
    letter-spacing: -0.03em;
    margin-bottom: 12px;
  }

  .doc-lead {
    font-size: 18px;
    color: var(--text-muted);
    margin-bottom: 20px;
    line-height: 1.6;
  }

  .doc-h2 {
    font-size: 24px;
    font-weight: 700;
    letter-spacing: -0.02em;
    margin-bottom: 20px;
  }

  .doc-h3 {
    font-size: 15px;
    font-weight: 600;
    color: #ccc;
    margin: 28px 0 10px;
  }

  .doc-p {
    font-size: 14.5px;
    color: var(--text-muted);
    line-height: 1.75;
    margin-bottom: 16px;
  }

  .doc-note {
    font-size: 13px;
    color: #555;
    line-height: 1.65;
    padding: 12px 16px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    margin-top: 16px;
  }

  code {
    font-family: var(--mono);
    font-size: 0.88em;
    color: #a5b4fc;
    background: rgba(165,180,252,0.08);
    padding: 2px 6px;
    border-radius: 4px;
  }

  .badge-row {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    margin-top: 16px;
  }

  .badge {
    font-size: 11.5px;
    font-weight: 500;
    padding: 4px 12px;
    border-radius: 100px;
    background: var(--surface-2);
    border: 1px solid var(--border-2);
    color: var(--text-muted);
  }

  .badge.green { color: #22c55e; border-color: rgba(34,197,94,0.3); background: rgba(34,197,94,0.06); }

  /* Capabilities */
  .cap-grid {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .cap-card {
    display: flex;
    gap: 16px;
    padding: 20px;
    background: var(--surface);
    border-radius: 10px;
    border: 1px solid var(--border);
  }

  .cap-icon {
    flex-shrink: 0;
    width: 34px;
    height: 34px;
    background: var(--bg);
    border: 1px solid var(--border-2);
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #555;
    margin-top: 2px;
  }

  .cap-card h3 {
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 6px;
    color: #e2e8f0;
  }

  .cap-card p {
    font-size: 13.5px;
    color: var(--text-muted);
    line-height: 1.65;
  }

  /* Code blocks */
  .code-block {
    background: var(--surface);
    border: 1px solid var(--border-2);
    border-radius: 9px;
    padding: 14px 18px;
    margin: 10px 0;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .code-block.xml {
    overflow-x: auto;
  }

  .code-block pre {
    font-family: var(--mono);
    font-size: 12.5px;
    color: #888;
    line-height: 1.6;
    white-space: pre;
  }

  .code-line {
    display: flex;
    gap: 10px;
    align-items: baseline;
    font-family: var(--mono);
    font-size: 13px;
  }

  .prompt {
    color: #3b82f6;
    flex-shrink: 0;
  }

  /* State table */
  .state-table {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-top: 16px;
  }

  .state-row {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 10px 14px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
  }

  .state-code {
    font-family: var(--mono);
    font-size: 12px;
    font-weight: 600;
    padding: 3px 10px;
    border-radius: 5px;
    white-space: nowrap;
    min-width: 160px;
  }

  .state-code.normal { color: #e2e8f0; background: rgba(255,255,255,0.05); }
  .state-code.warn { color: #f59e0b; background: rgba(245,158,11,0.1); }
  .state-code.high { color: #ef4444; background: rgba(239,68,68,0.1); }
  .state-code.stress { color: #f97316; background: rgba(249,115,22,0.1); }

  .state-label {
    font-size: 13px;
    color: var(--text-muted);
  }

  /* Config table */
  .config-table {
    border: 1px solid var(--border);
    border-radius: 10px;
    overflow: hidden;
    margin: 16px 0;
  }

  .config-row {
    display: grid;
    grid-template-columns: 140px 80px 1fr;
    gap: 12px;
    padding: 12px 16px;
    font-size: 13px;
    border-bottom: 1px solid var(--border);
    align-items: center;
  }

  .config-row:last-child { border-bottom: none; }

  .config-row.header {
    font-size: 10.5px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: var(--text-dim);
    background: var(--surface-2);
  }

  .config-row span { color: var(--text-muted); }

  /* Footer */
  .doc-footer {
    padding-top: 32px;
    text-align: center;
    font-size: 13px;
    color: var(--text-dim);
  }

  .doc-footer a { color: #555; transition: color 0.15s; }
  .doc-footer a:hover { color: #fff; }

  /* Right TOC */
  .toc {
    position: sticky;
    top: 80px;
    height: fit-content;
    padding: 48px 16px 48px 24px;
  }

  .toc-label {
    font-size: 10.5px;
    font-weight: 700;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--text-dim);
    margin-bottom: 12px;
  }

  .toc-link {
    display: block;
    font-size: 12.5px;
    color: var(--text-dim);
    padding: 5px 0;
    border-left: 2px solid transparent;
    padding-left: 10px;
    transition: color 0.15s, border-color 0.15s;
  }

  .toc-link:hover { color: #aaa; }

  .toc-link.active {
    color: #fff;
    border-left-color: #3b82f6;
  }

  @media (max-width: 1100px) {
    .toc { display: none; }
    .docs-root { grid-template-columns: 200px 1fr; }
  }

  @media (max-width: 700px) {
    .docs-root { grid-template-columns: 1fr; }
    .sidebar {
      position: static;
      height: auto;
      border-right: none;
      border-bottom: 1px solid var(--border);
      padding: 20px 0;
    }
    .content { padding: 32px 20px; }
    .state-row { flex-direction: column; align-items: flex-start; gap: 8px; }
    .state-code { min-width: unset; }
    .config-row { grid-template-columns: 1fr 60px; }
    .config-row span { display: none; }
    .config-row.header span:last-child { display: none; }
  }
</style>

// web/src/app/docs/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { Github, Sun, Moon } from "lucide-react";
import Link from "next/link";

export default function DocsPage() {
  const [isDark, setIsDark] = useState(true);

  useEffect(() => {
    const html = document.documentElement;
    if (isDark) {
      html.classList.add('dark');
      html.style.colorScheme = 'dark';
    } else {
      html.classList.remove('dark');
      html.style.colorScheme = 'light';
    }
  }, [isDark]);

  return (
    <div className="min-h-screen bg-white dark:bg-black text-black dark:text-white transition-colors duration-300 flex flex-col lg:flex-row">
      {/* Sidebar */}
      <aside className="w-full lg:w-72 border-b lg:border-r border-black/10 dark:border-white/5 h-auto lg:h-screen lg:sticky lg:top-0 p-8 bg-white dark:bg-black">
        <div className="mb-12">
          <Link href="/" className="text-xl font-medium hover:opacity-70 transition-opacity">Monarx</Link>
        </div>
        
        <nav className="space-y-1">
          <SidebarLink href="#overview" label="Overview" active />
          <SidebarLink href="#capabilities" label="Capabilities" />
          <SidebarLink href="#installation" label="Installation" />
          <SidebarLink href="#usage" label="Usage" />
          <SidebarLink href="#configuration" label="Configuration" />
          <SidebarLink href="#auto-start" label="Auto-Start" />
        </nav>

        <div className="mt-12 hidden lg:block">
          <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-black/30 dark:text-white/30 mb-4 px-3">Resources</h4>
          <a 
            href="https://github.com/dinexh/Monarx" 
            className="block px-3 py-2 text-sm text-black/60 dark:text-white/60 hover:text-black dark:hover:text-white transition-colors rounded-lg hover:bg-black/5 dark:hover:bg-white/5"
          >
            GitHub Repo
          </a>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 max-w-4xl mx-auto px-6 lg:px-12 py-12 lg:py-24">
        <Link href="/" className="lg:hidden flex items-center gap-2 text-black/60 dark:text-white/60 text-sm mb-12 hover:text-black dark:hover:text-white transition-colors">
          ← Back to Home
        </Link>

        <header className="mb-16">
          <div className="text-xs text-black/30 dark:text-white/30 uppercase tracking-widest mb-4">Documentation</div>
          <h1 className="text-5xl font-light mb-6 tracking-tight">Monarx</h1>
          <p className="text-xl text-black/60 dark:text-white/40 leading-relaxed">
            Comprehensive guide to the intelligent macOS system monitoring agent. 
            Track performance, identify memory pressure, and monitor top processes.
          </p>
        </header>

        <Section id="overview" title="Overview">
          <p>
            Monarx is a lightweight, real-time system monitoring application designed exclusively for macOS. 
            It hooks into native macOS kernel interfaces and system APIs to provide deep visibility into 
            CPU usage, detailed memory breakdown, and system health alerts directly in your menu bar.
          </p>
        </Section>

        <Section id="capabilities" title="Core Capabilities">
          <div className="grid sm:grid-cols-2 gap-6 mt-8">
            <CapabilityItem 
              title="Native Menu Bar UI" 
              description="Monitor all vital system stats from a clean, non-intrusive menu bar dropdown." 
            />
            <CapabilityItem 
              title="Memory Pressure" 
              description="Identify Wired, Active, Compressed, and Cached memory states with 1-second updates." 
            />
            <CapabilityItem 
              title="Process Intelligence" 
              description="See exactly which processes are consuming CPU and memory with the ability to kill them." 
            />
            <CapabilityItem 
              title="Threat Detection" 
              description="Stay informed with native notifications for high resource usage and lag risks." 
            />
          </div>
        </Section>

        <Section id="installation" title="Installation">
          <p className="mb-6">
            Monarx requires Python 3.9+ and can be installed via pip. 
            It uses `rumps` for the menu bar and `psutil` for resource tracking.
          </p>
          <div className="bg-black dark:bg-[#0d0d0d] rounded-xl border border-black/10 dark:border-white/5 overflow-hidden">
            <div className="flex items-center gap-2 px-4 py-2 bg-black/10 dark:bg-white/5 text-[10px] font-mono text-black/30 dark:text-white/30">
              Terminal
            </div>
            <pre className="p-6 text-sm font-mono text-blue-500 dark:text-blue-400 leading-relaxed overflow-x-auto">
{`# Clone the repository
git clone https://github.com/dinexh/Monarx.git
cd Monarx

# Create and activate virtual environment
python3 -m venv .venv
source .venv/bin/activate

# Install dependencies
pip install psutil rumps pyobjc`}
            </pre>
          </div>
        </Section>

        <Section id="usage" title="Usage">
          <p className="mb-6">
            Run the application using the entry point script. 
            The app will automatically initialize and appear in your macOS menu bar.
          </p>
          <div className="bg-black/5 dark:bg-white/5 border border-black/10 dark:border-white/5 p-6 rounded-lg">
            <code className="text-sm font-mono text-black dark:text-white">python main.py</code>
          </div>
        </Section>

        <Section id="configuration" title="Configuration">
          <p className="mb-6">
            Thresholds and intervals can be configured in `core/config.py`. 
            These settings determine when notifications are triggered.
          </p>
          <div className="bg-black dark:bg-[#0d0d0d] rounded-xl border border-black/10 dark:border-white/5 overflow-hidden">
             <div className="flex items-center gap-2 px-4 py-2 bg-black/10 dark:bg-white/5 text-[10px] font-mono text-black/30 dark:text-white/30 uppercase tracking-widest">
              Python Config
            </div>
            <pre className="p-6 text-sm font-mono text-black/60 dark:text-white/60 leading-relaxed overflow-x-auto">
{`CPU_LIMIT = 85      # Alert when CPU exceeds 85%
MEM_LIMIT = 80      # Alert when Memory exceeds 80%
SWAP_LIMIT = 20     # Alert when Swap exceeds 20%
CHECK_EVERY = 5     # Refresh interval (seconds)
COOLDOWN = 120      # Cooldown for repeat alerts`}
            </pre>
          </div>
        </Section>

        <Section id="auto-start" title="Auto-Start (macOS)">
          <p className="mb-6">
            To have Monarx start automatically on login, create a LaunchAgent plist file.
          </p>
          <div className="bg-black dark:bg-[#0d0d0d] rounded-xl border border-black/10 dark:border-white/5 overflow-hidden">
            <div className="flex items-center gap-2 px-4 py-2 bg-black/10 dark:bg-white/5 text-[10px] font-mono text-black/30 dark:text-white/30">
               com.monarx.plist
            </div>
            <pre className="p-6 text-[13px] font-mono text-black/40 dark:text-white/40 leading-relaxed overflow-x-auto">
{`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "...">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.monarx</string>
    <key>ProgramArguments</key>
    <array>
        <string>/path/to/.venv/bin/python</string>
        <string>/path/to/Monarx/main.py</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>`}
            </pre>
          </div>
        </Section>

        <footer className="mt-24 pt-12 border-t border-black/10 dark:border-white/5 flex items-center justify-between text-black/40 dark:text-white/40 text-sm">
          <p>© 2026 Monarx. Open Source Software.</p>
          <div className="flex gap-6">
            <a href="https://github.com/dinexh/Monarx" className="hover:text-black dark:hover:text-white transition-colors">GitHub</a>
            <Link href="/" className="hover:text-black dark:hover:text-white transition-colors">Home</Link>
          </div>
        </footer>
      </main>

      {/* Right Sidebar (On this page) */}
      <aside className="hidden xl:block w-64 h-screen sticky top-0 p-12 border-l border-black/10 dark:border-white/5 bg-white dark:bg-black">
        <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-black/30 dark:text-white/30 mb-6">On this page</h4>
        <nav className="space-y-4">
          <OnPageLink href="#overview" label="Overview" />
          <OnPageLink href="#capabilities" label="Capabilities" />
          <OnPageLink href="#installation" label="Installation" />
          <OnPageLink href="#usage" label="Usage" />
          <OnPageLink href="#configuration" label="Configuration" />
          <OnPageLink href="#auto-start" label="Auto-Start" />
        </nav>
      </aside>

      {/* Theme Toggle - Fixed at bottom */}
      <button
        onClick={() => setIsDark(!isDark)}
        className="fixed bottom-8 right-8 w-14 h-14 rounded-full bg-black dark:bg-white text-white dark:text-black flex items-center justify-center shadow-lg hover:scale-110 active:scale-95 transition-all z-50 border-2 border-black/10 dark:border-white/10"
        aria-label="Toggle theme"
      >
        {isDark ? <Sun size={22} /> : <Moon size={22} />}
      </button>
    </div>
  );
}

function Section({ id, title, children }: { id: string, title: string, children: React.ReactNode }) {
  return (
    <section id={id} className="mb-20 scroll-mt-32">
      <h2 className="text-2xl font-medium mb-6">{title}</h2>
      <div className="text-black/60 dark:text-white/60 leading-relaxed space-y-4">
        {children}
      </div>
    </section>
  );
}

function SidebarLink({ href, label, active = false }: { href: string, label: string, active?: boolean }) {
  return (
    <Link 
      href={href} 
      className={`block px-3 py-2 text-sm rounded-lg transition-all ${
        active 
        ? "bg-black/10 dark:bg-white/10 text-black dark:text-white font-medium" 
        : "text-black/60 dark:text-white/60 hover:text-black dark:hover:text-white hover:bg-black/5 dark:hover:bg-white/5"
      }`}
    >
      {label}
    </Link>
  );
}

function OnPageLink({ href, label }: { href: string, label: string }) {
  return (
    <Link href={href} className="block text-xs text-black/40 dark:text-white/40 hover:text-black dark:hover:text-white transition-colors">
      {label}
    </Link>
  );
}

function CapabilityItem({ title, description }: { title: string, description: string }) {
  return (
    <div className="bg-black/5 dark:bg-white/5 border border-black/10 dark:border-white/5 p-6 rounded-lg">
      <h4 className="text-sm font-medium mb-2">{title}</h4>
      <p className="text-xs text-black/60 dark:text-white/60 leading-relaxed">{description}</p>
    </div>
  );
}
